### ISSUE TITLE
Example view.xml & index.html files

### ISSUE THREAD

**Issue by dischord01** [hortonworks-gallery/ambari-iframe-view#1]
Could you show what a view.xml and index.html file look like as a iframe example with more than just the one example service? I have several services installed in Ambari and on remote servers in our cluster (HUE, Zeppelin, Solr) and I'm having issues getting the index + view to sync up.

**Comment by abajwa-hw** [comment]
You would need to run through the same steps multiple times, one for each service you want to embed in iFrame. Here is a sample of how to automate this for one service:
https://github.com/abajwa-hw/security-workshops/blob/master/scripts/setup_solr_banana.sh#L57-L76

You can follow the same steps for each service to be emedded

**Comment by dischord01** [comment]
Thanks Ali, that worked!

Regards,

S. Brad Sollar
